### ISSUE TITLE
Long Term Plan for Scam Tokens

### ISSUE THREAD

**Issue by Armeanio** [spectrum-finance/token-logos#3]
The hardest part of a decentralized dex is fake tokens. 

The easiest way to identify that for users will be visual through perhaps a logo and a popup warning that they are going to interact with something that is of high risk. 

The question becomes one of governance and auditing. Which is admittedly a clusterfuck that adds additional complexity. 

It would be nice to see project info/stats/links etc on the frontend to allow users to DYOR and minimize risk.

**Comment by yasha-black** [comment]
Resolved
https://github.com/ergolabs/ergo-dex-frontend/releases/tag/1.3.5
Also, check UI - app.ergodex.io
