### ISSUE TITLE
Ogre token isn't filterable in the pool view

### ISSUE THREAD

**Issue by ErgoWhale** [spectrum-finance/token-logos#42]
The PR to make Ogre token visible was merged in https://github.com/ergolabs/ergo-dex-asset-icons/pull/39. There is a liquidity pool of Ergo/Ogre, but that's not visible in the "Pools Overview" even when you search by Ogre.

![image](https://user-images.githubusercontent.com/112586130/188340797-b999cfb1-6190-419d-be49-d40a4c13586d.png)

If you actually use a browser where you're connected with your wallet and you own Ogre, it seems like it shows up.

I haven't been able to find Ogre in the search results until just like maybe an hour ago, so maybe something is in the process of being rebooted?

**Comment by yasha-black** [comment]
@ErgoWhale 
#39 was made to display the toke icon
This repo is for that purpose

Request token addition https://github.com/ergolabs/default-token-list to add your token to the default token list

You also can use ogre if you import it. Use search in "select token" modal
<img width="490" alt="image" src="https://user-images.githubusercontent.com/43601702/188392490-3d6f4487-78b6-4974-b5c0-87e5607d8663.png">

**Comment by ErgoWhale** [comment]
Roger that. I was thinking there was a "search" on the pools page, but now I get it. Closing this in favor of https://github.com/ergolabs/default-token-list/pull/12
